In [1]:
%matplotlib inline


# Multiclass classification with under-sampling


Some balancing methods allow for balancing dataset with multiples classes.
We provide an example to illustrate the use of those methods which do
not differ from the binary case.




In [25]:
# Authors: Guillaume Lemaitre <g.lemaitre58@gmail.com>
# License: MIT

from collections import Counter

from sklearn.datasets import load_iris
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split

from imblearn.datasets import make_imbalance
from imblearn.under_sampling import NearMiss
from imblearn.pipeline import make_pipeline
from imblearn.metrics import classification_report_imbalanced

print(__doc__)

RANDOM_STATE = 42

# Create a folder to fetch the dataset
iris = load_iris()
X, y = make_imbalance(iris.data, iris.target, ratio={0: 25, 1: 50, 2: 50},
                      random_state=0) #under-sampling method

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=RANDOM_STATE)

print('Training target statistics: {}'.format(Counter(y_train)))
print('Testing target statistics: {}'.format(Counter(y_test)))

# Create a pipeline
pipeline = make_pipeline(NearMiss(version=2, random_state=RANDOM_STATE),
                         LinearSVC(random_state=RANDOM_STATE))
pipeline.fit(X_train, y_train)

# Classify and report the results
print(classification_report_imbalanced(y_test, pipeline.predict(X_test)))

Automatically created module for IPython interactive environment
Training target statistics: Counter({1: 38, 2: 38, 0: 17})
Testing target statistics: Counter({1: 12, 2: 12, 0: 8})
                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      1.00      1.00      1.00      1.00         8
          1       1.00      0.83      1.00      0.91      0.91      0.82        12
          2       0.86      1.00      0.90      0.92      0.95      0.91        12

avg / total       0.95      0.94      0.96      0.94      0.95      0.90        32



In [23]:
print(len(iris['data']))
print(iris['target'])
print(len(iris['target']))
y= iris['target']
import numpy as np
labels_0 = np.extract(y==0,y)
print(len(labels_0))
labels_1 = np.extract(y==1,y)
print(len(labels_1))
labels_2 = np.extract(y==2,y)
print(len(labels_2))

150
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
150
50
50
50


In [12]:
print(type(iris['target']))

<class 'numpy.ndarray'>


In [13]:
print(X)

[[ 5.2  3.4  1.4  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 5.4  3.7  1.5  0.2]
 [ 4.5  2.3  1.3  0.3]
 [ 4.7  3.2  1.3  0.2]
 [ 5.2  3.5  1.5  0.2]
 [ 4.4  3.   1.3  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.5  4.2  1.4  0.2]
 [ 5.   3.2  1.2  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 4.9  3.1  1.5  0.1]
 [ 5.7  3.8  1.7  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 5.8  4.   1.2  0.2]
 [ 4.8  3.   1.4  0.3]
 [ 5.3  3.7  1.5  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 4.8  3.1  1.6  0.2]
 [ 5.2  4.1  1.5  0.1]
 [ 5.4  3.9  1.3  0.4]
 [ 4.4  3.2  1.3  0.2]
 [ 6.9  3.1  4.9  1.5]
 [ 5.5  2.4  3.8  1.1]
 [ 6.1  2.8  4.7  1.2]
 [ 5.6  3.   4.5  1.5]
 [ 6.1  2.9  4.7  1.4]
 [ 6.   2.9  4.5  1.5]
 [ 5.2  2.7  3.9  1.4]
 [ 5.7  3.   4.2  1.2]
 [ 6.   2.7  5.1  1.6]
 [ 6.3  2.3  4.4  1.3]
 [ 5.7  2.9  4.2  1.3]
 [ 4.9  2.4  3.3  1. ]
 [ 5.4  3.   4.5  1.5]
 [ 5.6  2.5  3.9  1.1]
 [ 5.   2.3  3.3  1. ]
 [ 5.8  2.7  3.9  1.2]
 [ 6.6  2.9  4.6  1.3]
 [ 6.3  2.5  4.9  1.5]
 [ 5.7  2.6

In [14]:
print(len(X))

125


In [15]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [21]:
import numpy as np
labels_0 = np.extract(y==0,y)
print(len(labels_0))
labels_1 = np.extract(y==1,y)
print(len(labels_1))
labels_2 = np.extract(y==2,y)
print(len(labels_2))

25
50
50
